services:
  web:
    build: src/web
    ports:
      - "8501:8501"
    environment:
      HOST: "backend:8000"
      BACKEND_SERVER: "backend:8000"
      OLLAMA_SERVER: ""
      OPENAI_API_KEY: "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"
      GROQ_API_KEY: "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"
    networks:
      - internal
  
  backend:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: "db"
      HOST: "0.0.0.0"
    networks:
      - internal
      
  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge