services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/code
    depends_on:
      - db
  
  backend:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    depends_on:
      - db