services:
  web:
    build: src/web
    ports:
      - "8501:8501"
    environment:
      HOST: "backend:8000"
      BACKEND_SERVER: "backend:8000"
      OLLAMA_SERVER: ""
      OPENAI_API_KEY: ${{ secrets.aikey }}
      GROQ_API_KEY: "gsk_XXXX"
    networks:
      - internal
  
  backend:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: "db"
      HOST: "0.0.0.0"
    networks:
      - internal
      
  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge