services:
  web:
    build: src/web
    ports:
      - "8501:8501"
    networks:
      - internal
  
  backend:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=redis://db:6379
    networks:
      - internal
      
  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal