services:
  web:
    build: src/web
    ports:
      - "8501:8501"
    depends_on:
      - backend
  
  backend:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./src/database:/data/db