services:
  web:
    build: src/web
    ports:
      - "8501:8501"
    environment:
      HOST: "backend:8000"
      BACKEND_SERVER: "backend:8000"
      OLLAMA_SERVER: ""
      OPENAI_API_KEY: "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"
      GROQ_API_KEY: "gsk_XXXX"
    networks:
      - internal
  
  backend:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: "db"
      HOST: "0.0.0.0"
    networks:
      - internal
      
  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge