services:
  web:
    build: ./web
    ports:
      - "8501:8501"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"